export const SET_REPOS = 'SET_REPOS';
export const SET_PAGE = 'SET_PAGE';
export const SET_NEXT_PAGE = 'SET_NEXT_PAGE';
export const LOAD_REPOS_FAILED = 'LOAD_REPOS_FAILED';
export const LOAD_REPOS_SUCCESS = 'LOAD_REPOS_SUCCESS';
export const LOADING = 'LOADING';
export const RELOADING_REPO = 'RELOADING_REPO';
export const RELOADING_REPO_FINISHED = 'RELOADING_REPO_FINISHED';

export const SET_USER_INPUT = 'SET_USER_INPUT';
export const SET_SORT_BY = 'SET_SORT_BY';